### PR TITLE
limit long usernames in menubar in user table

### PR DESCRIPTION
**Pull request by loomis**
Connected to #729.

### CODE REVIEW

**Comment by loomis** [comment]
The screenshot shows the user table with the limited username sizes and shows what happens in the menubar with long usernames (value modified by hand through the browser). 

usernames limited in length in menubar and user table

**Comment by konstan** [comment]
Minor comment.  If I hoover over the ellipsized username in the upper right corner - it disappears.
screen shot 2017-06-22 at 11 54 30

**Comment by loomis** [comment]
Ok, will take a look.

**Comment by konstan** [comment]
All the rest seems OK.  
Can be merged.

**Comment by loomis** [comment]
@konstan I've committed a fix for the transparency.  Would you like to test it before I merge?

**Pull request merged**
