### PR TITLE
new: updated tables to be responsive and use as much space as possible on small screens...

### LINKED ISSUE #267: Improve rendering of tables on mobile devices (especially on mobile phones)
Tables are currently not responsive.
They should be responsive and use as much space as possible.

### PR DESCRIPTION
**Pull request by schaubl**
... like mobile phones.

Fix #267.

### CODE REVIEW

**Comment by rbf** [comment]
@schaubl 
Please take a look at my comments in form of commits above, and let my know if you'd like to discuss some points.
If you agree on those and once you have double-checked that this works also on your side :wink:, I'll merge this PR tomorrow.

**Comment by rbf** [comment]
BTW, the mobile version looks much better with this PR, thanks @schaubl :smiley::+1:

Before:

screen shot 2015-04-07 at 18 51 53

After:

screen shot 2015-04-07 at 18 52 06

**Comment by schaubl** [comment]
@rbf : Thanks for the screenshots

**Comment by rbf** [comment]
After review with @schaubl I applied the agreed changes (see comment in my previous commit 542353b).
I'm merging now this PR.

**Comment by schaubl** [comment]
Noooooooooooooooo

**Comment by rbf** [comment]
@schaubl Now, yes, I'm merging :wink:

**Comment by schaubl** [comment]
:+1:

**Pull request merged**
